name: Deploy specific HTML page to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job (Optional)
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build  # Replace with your build command if needed
      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish-dir: ./dist  # Replace with your build output directory
          publish-branch: gh-pages

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: https://adamhongbst.github.io/ShowUltraman/ShowScratchWithMenu.html
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy specific HTML page
        run: |
          mkdir -p ${{ github.workspace }}/.github/pages
          echo "<meta http-equiv=\"refresh\" content=\"0; url=https://adamhongbst.github.io/ShowUltraman/ShowScratchWithMenu.html\">" > ${{ github.workspace }}/.github/pages/index.html
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
